Repository jellyfin/jellyfin-sdk-kotlin, pull requests merged in 2023-01, with the labels that each got.

#626 Use lazy injection for openapi-generator CLI
  openapi-generator/src/main/kotlin/org/jellyfin/openapi/Main.kt
  openapi-generator/src/main/kotlin/org/jellyfin/openapi/MainModule.kt
  openapi-generator/src/main/kotlin/org/jellyfin/openapi/cli/BaseCommand.kt
  openapi-generator/src/main/kotlin/org/jellyfin/openapi/cli/GenerateCommand.kt
  openapi-generator/src/main/kotlin/org/jellyfin/openapi/cli/MainCommand.kt
  openapi-generator/src/main/kotlin/org/jellyfin/openapi/cli/VerifyCommand.kt
Labels: bug, openapi-generator

#632 Extend organization Node.js Renovate config
  renovate.json
Labels: dependencies

#636 Bump Android SDK to 33
  gradle/libs.versions.toml
  jellyfin-core/build.gradle.kts
Labels: dependencies

#638 Explicitly set Accept header in KtorClient
  jellyfin-api/api/jellyfin-api.api
  jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/ApiClient.kt
  jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt
Labels: enhancement, backport

#639 Update java-cli sample to use UserApiExtensionsKt
  samples/java-cli/src/main/java/org/jellyfin/sample/cli/Main.java
Labels: bug

#640 Increase default socket timeout value to 30 seconds
  jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/HttpClientOptions.kt
Labels: enhancement

#646 Remove gradlew-update.yaml workflow
  .github/workflows/gradlew-update.yaml
Labels: refactor

#650 refactor: convert Long to Duration for `HttpClientOptions`
  jellyfin-api/api/jellyfin-api.api
  jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/HttpClientOptions.kt
  jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt
  jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/sockets/OkHttpWebsocketSession.kt
  jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt
Labels: enhancement
