Repository jellyfin/jellyfin-sdk-kotlin, pull requests merged in 2024-05, with the labels that each got.

#916 Flow on Dispatchers.IO by default in LocalServerDiscovery
  jellyfin-core/src/jvmCommonMain/kotlin/org/jellyfin/sdk/discovery/LocalServerDiscovery.kt
Labels: enhancement

#923 Fix a kdoc typo
  jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/ssl/HandshakeCertificateException.kt
Labels: bug, docs

#925 Fix javadoc using wrong name
  jellyfin-api-ktor/build.gradle.kts
  jellyfin-api/build.gradle.kts
  jellyfin-core/build.gradle.kts
  jellyfin-model/build.gradle.kts
Labels: bug

#926 Use data object for RecommendedServerIssue.MissingVersion
  jellyfin-core/api/android/jellyfin-core.api
  jellyfin-core/api/jvm/jellyfin-core.api
  jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/RecommendedServerIssue.kt
Labels: enhancement

#931 Disable flaky unit tests
  jellyfin-core/src/jvmTest/kotlin/org/jellyfin/sdk/api/SSLResolverTests.kt
Labels: bug

#942 Add homedia as third party client
  docs/guide/getting-started.md
Labels: docs
